### PR TITLE
Create contributors.md

### PR DESCRIPTION
**Pull request by pizzalord22**
added the contributors.md file

### CODE REVIEW

**Comment by solidassassin** [comment]
Not sure if this is needed (the `contributors` tab is a thing), but wouldn't it be better to just use Github's API to get the contributors? Maybe show them by typing a certain command (since you can't easily see contributors on Discord)?

**Comment by pizzalord22** [comment]
yes but i needed an hacktober pr

**Comment by realtux** [comment]
don't be a cheater, at least link to everyone's github and check to make sure each person actually contributed something useful

**Comment by solidassassin** [comment]
Github's API isn't complicated, it'll provide you with all the info you need and a command to view the contributors on Discord would have way more value. Also `contributors.md` wouldn't need to be constantly updated. Not sure now, but I believe the some commands do utilize Github's API making them good examples.

**Pull request closed without merging**
