### PR TITLE
Improvements to spam ls

### PR DESCRIPTION
**Pull request by a-random-lemurian**
This pull request contains improvements to the `felix spam ls` command.

- [x] pad spam id numbers with spaces
- [x] implement pagination
  - [x] decide page size (25; felix sends spam rules in bundles of 25 per message so logical)
  - [x] decide whether to start at zero or one

### CODE REVIEW

**Comment by a-random-lemurian** [comment]
Regarding 6d69538b6ced6fd5440fe84bf2d6ee58a6c8162a, should the page numbers start at zero or one?

**Comment by ccall48** [comment]
I was thinking 0, but realistically it would probably make more sense in the bot to make first page as 1 when interacting with it.

**Comment by a-random-lemurian** [comment]
> I was thinking 0, but realistically it would probably make more sense in the bot to make first page as 1 when interacting with it.

Alright, we'll start with page 1.

**Comment by a-random-lemurian** [comment]
Should be all good now with 0ae5cc7

**Comment by brtwrst** [comment]
This seems not to work correctly 
image

Also what exactly is the benefit of this?
Nobody really knows on what page a specific rule is so everyone will just run the basic command that return all results anyway.

**Comment by a-random-lemurian** [comment]
> This seems to not work correctly image
> 
> Also what exactly is the benefit of this? Nobody really knows on what page a specific rule is so everyone will just run the basic command that return all results anyway.

Did you try `felix spam ls 2`?

**Comment by brtwrst** [comment]
* Still don't see the use for this.
* 11 commits to change 10 lines
* not ideal code structure (factoring a simple operation out into a badly named function that is only ever called once)

I don't think we need this

**Comment by a-random-lemurian** [comment]
Response to @brtwrst 

> * Still don't see the use for this.

We can now view individual pages of the spam list, which prevents clutter and also makes sure that in the future when our spam list is much larger Felix won't be ratelimited.

> * 11 commits to change 10 lines

We can always squash-merge.

> * not ideal code structure (factoring a simple operation out into a badly named function that is only ever called once)

I'm working on it. Additionally, I have another `felix spam search` command in the works that will need to also assemble a spam list so I'm factoring it out into a new function.

**Comment by brtwrst** [comment]
Viewing single pages has no real use if you don't know where the thing, that you're looking for, is at. 
Maybe a spamls search command would be more useful. 
If you want to make it more compact to print out everything you could just send it as a big text file.

**Comment by a-random-lemurian** [comment]
Per discussion on Discord, this isn't necessary. Closing

**Pull request closed without merging**
