### PR TITLE
Delete malicious files

### PR DESCRIPTION
**Pull request by solidassassin**
Delete malicious and harmful files posted by members. For now only `.exe` files will be deleted and reported, reason being they've been causing most of the problems.

### CODE REVIEW

**Comment by brtwrst** [comment]
Just one thing i would like you to add.
When it deletes a message because of an attachment - don't just print the name of the attachment in the report. Attach the forbidden file to the report message - so it doesn't get lost.
This way we can examine it and decide if we want to take further steps with the ofender.

**Comment by aveliz1999** [comment]
I did some testing and found that the width and height properties of the attachment are only set for valid images and videos (so no just renaming to a different file extension).
You can use that for whitelisting so that only files that discord can render (images/videos) can be sent rather rather than blacklisting specific extensions

**Comment by solidassassin** [comment]
Is it really a good idea to block all files that can't be rendered?

**Comment by aveliz1999** [comment]
I mean, what other type of file would be sent?
Text and code can be sent as emkc snippets
And any executable is a major risk

**Comment by realtux** [comment]
please do not whitelist. you'll invariably not whitelist enough and cause user confusion. just blacklist executables.

**Comment by brtwrst** [comment]
as in: just .exe files?

**Comment by realtux** [comment]
that sounds good. we've allowed 100% of files for 1.5 years. the solution to one incident is not to lower than number to 20%, it's to lower it to 99%.

**Comment by brtwrst** [comment]
not neccesarily
when you detect a bad attachment, save it to a discord.File object
and just add it to the report message. (superuser has some code reading attachments, graph has some code sending files as attachments)

This way you temporarily save the file to RAM.

**Pull request merged**
