### PR TITLE
add/remove/list spam from felix auto jail if bad link sent except for…

### PR DESCRIPTION
**Pull request by ccall48**
add/remove/list spam from felix auto jail if bad link sent except for friends/admin users.

### CODE REVIEW

**Comment by brtwrst** [comment]
No real reason to load the spam list from file every time a message is sent right?
It only has to be loaded at startup and if the list changes (add/rm) command.

Also there is a big block of commented code in there.

**Comment by brtwrst** [comment]
you're still loading the list from file on every message

**Comment by brtwrst** [comment]
also please squash it down to one commit

**Comment by ccall48** [comment]
> also please squash it down to one commit

i'll be honest, i got no idea how to do that.

**Comment by brtwrst** [comment]
then either save all your changes "manually" -> reset your git repo to the original repo's state -> copy in your changes -> make one single commit -> force push

or learn how to squash/fixup, there's enough resources out there seriously

**Comment by ccall48** [comment]
I rebased it, but it did it to master branch arrgh! i'll close this and push from there ig 😭

**Comment by brtwrst** [comment]
rebasing the master branch is correct
then just force push and done

now we have 2 dead PRs  yay

**Pull request closed without merging**
