### PR TITLE
Added method purger_user_time

### PR DESCRIPTION
**Pull request by ThreshMain**
method purger_user_time removes all messages from user in every channel within the last X seconds which defaults to 100

### CODE REVIEW

**Comment by brtwrst** [comment]
A few things.
* Default could be 5 minutes I think
* You can use the parameter `after` when using purge instead of the check.
* This will only look at the 100 most recent messages in each channel (the default for the `limit` parameter of purge)

**Comment by ThreshMain** [comment]
Should be fixed now I was also wondering why is there `before=None` in every other purge command? Was it necessary in older versions?

**Comment by brtwrst** [comment]
don't remember

**Comment by brtwrst** [comment]
I had some issues when testing this locally.
If there is a channel where the bot does not have "read message history" or "manage messages" permissions then it will crash.
my quick solution was to wrap the deletion command
```python
from discord import Forbidden
try:
    await channel.purge(limit=None, check=check, after=after)
except Forbidden:
    continue
```

Also setting limit to None seems bad. 
Set it to something sensible like 10-20 per minute that is being purged. If it turns out not to be enough the command can just be run a second time.

**Pull request merged**
