### PR TITLE
Added support for command-line arguments

### PR DESCRIPTION
**Pull request by Minecraftian14**
eg:

Command>

felix run java
Argument 1
Arg 2
Well, just here
```java
import java.util.List;
public class Experiment {
  public static void main(String[] args) {
    List.of(args).forEach(System.out::println);
  }
}
```

Output>

Here is your output @Marxia 1114#0523
```
Argument 1
Arg 2
Well, just here
```

### CODE REVIEW

**Comment by solidassassin** [comment]
Moving forward Felix will not support code execution. This is apparent in commit fe98ea5. From now on code execution will be handled by [Piston Bot](https://github.com/engineer-man/piston-bot). You're free to make a pull request there, but I'd recommend to wait since the bot is in very early stages and a ton of things might change. I'm gonna close this issue now if you don't mind.

**Comment by Minecraftian14** [comment]
Yeah, sure, you can delete this branch too.

**Comment by solidassassin** [comment]
You wanted to merge from a branch which is on your own fork. So branch management is up to you ;)

**Comment by Minecraftian14** [comment]
Oh, well thanks for informimg that

**Pull request closed without merging**
