### PR TITLE
Add additional file extensions to snippet cog

### PR DESCRIPTION
**Pull request by aveliz1999**

### CODE REVIEW

**Comment by brtwrst** [comment]
How about you add all the filetypes that can be chosen on EMKC and then i merge it. This way nobody else has to do that later.

**Comment by brtwrst** [comment]
These are the selectable languages.
```
apex
azcli
bat
c
clojure
coffeescript
cpp
csharp
csp
css
dockerfile
fsharp
go
handlebars
html
ini
java
javascript
json
less
lua
markdown
msdax
mysql
objective-c
perl
pgsql
php
plaintext
postiats
powerquery
powershell
pug
python
r
razor
redis
redshift
ruby
rust
sb
scheme
scss
shell
sol
sql
st
swift
typescript
vb
xml
yaml
```
most languages should only have 1 file type. Some might have more (c++ has .h and .cpp)

**Comment by aveliz1999** [comment]
There you go brt.
Added an exception for Dockerfile since it doesn't have an extension

**Comment by brtwrst** [comment]
yeah the code is actually broken in some places but I'll fix it

**Pull request merged**
