### PR TITLE
http cats status codes

### PR DESCRIPTION
**Pull request by ThreshMain**
HTTP cats do not support all codes from HTTPStatus which caused empty embeds without an error message.
So I added all Http cats manually from their Github not the best solution but it works.

### CODE REVIEW

**Comment by brtwrst** [comment]
How about you parse the http.cat webpage when the cog is loaded and create the list from that insted of hardcoding it? The source seems simple enough. (view-source: https://http.cat/  + `CTRL+U`)

**Comment by brtwrst** [comment]
And make sure your branch is up to date with master before you begin to prevent the merge commits.

**Comment by ThreshMain** [comment]
Reopening pull request with automatic HTTP cat codes using bs4 web scraping.

**Comment by ThreshMain** [comment]
Removed bs4 and used regex instead.

**Comment by brtwrst** [comment]
* please make sure that in the end your pull request is not a bunch of commits that go back and forth with adding and removing stuff. Preferrably squash it down to 1 commit.
* Please don't use requests there is a aiohttp session provided in `self.client.session`. Reference some other commands that access APIs to see how to use it (felix gif).
* Please load the list of response codes in a task and don't call it directly from the init. Together with the requests usage this can break the whole cog. You can check other cogs (activities, aoc) to see tasks used in action.

**Pull request merged**
