### PR TITLE
Challenges cog finally here!

### PR DESCRIPTION
**Pull request by Pyroseza**

### CODE REVIEW

**Comment by brtwrst** [comment]
A few issues:
* You seem to not have pulled felix before starting your challenge cog so the branches have diverged and you have to fix that.
* The reload command is not needed. The plebs should not have the ability to reaload it - makes no sense.
Admins can already reload the whole cog with `felix reload challenge`
Also it is highly unlikely that the challenge.json will get changed without the bot restarting anyway.
* There are some strange/unused functions `obj_dict` `my_sort` which are not needed it seems.
* Some debug print statements are left.
* Try to make it PEP8 compliant  (line length)
* Create your own Exceptions and don't raise and catch the base Exception class.

**Comment by brtwrst** [comment]
Also take my name out of the commit message.
Commit messages have a specific purpose and this is not it.

**Comment by brtwrst** [comment]
image
also this seems like hot garbage
what am i supposed to do? Look up what eulerian paths are and think of my own challenge?
nah thanks

**Comment by Pyroseza** [comment]
I honestly wonder how that second conflict got in there, anyways all done now
@brtwrst ready when you are

**Comment by Pyroseza** [comment]
I'm having a tough time squashing them @brtwrst, honestly I've 3 different ways and I'm not succeeding, they still show up as many commits

**Pull request closed without merging**
