### PR TITLE
HTML is programming language regex

### PR DESCRIPTION
**Pull request by ThreshMain**
Very important update to stop all from believing that HTML is programming.

### CODE REVIEW

**Comment by brtwrst** [comment]
I don't get it

**Comment by Shivansh-007** [comment]
He meant the `a` is optional
Screenshot from 2020-11-18 13-33-18

**Comment by brtwrst** [comment]
i know what the regex does but why `html is programming language` 

But even to my non native english ears that sounds weird.

Miami is city.
Whiskey is drink.

**Comment by ThreshMain** [comment]
I feel the same way but still, I saw that like twice already and the original one I saw only if someone wanted to invoke the bot action.

**Comment by brtwrst** [comment]
this is not a "bot action"
this is an easteregg

**Comment by ThreshMain** [comment]
Ok

**Pull request closed without merging**
