### PR TITLE
Adding httpcat missing codes

### PR DESCRIPTION
**Pull request by Shivansh-007**
Adding the following new codes
```python
[
103, # EARLY_HINTS
418, # IM_A_TEAPOT
425
]
```

### CODE REVIEW

**Comment by brtwrst** [comment]
https://http.cat/103 is not available on http.cat
Why did you include it here?

**Comment by Shivansh-007** [comment]
Sorry, would have been added by mistake , lemme remove it

**Comment by Shivansh-007** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103#:~:text=The%20HTTP%20103%20Early%20Hints,is%20still%20preparing%20a%20response. 

Could see it here tho

**Comment by brtwrst** [comment]
i know the code exists.
But the command is about printing the cat pictures.
if no cat picture exists for 103 then it doesn not make sense to add it to the list of valid codes for the cat picture command.

**Pull request merged**
