### PR TITLE
[Feature] Stackoverflow Cog

### PR DESCRIPTION
**Pull request by Shivansh-007**
### Preview After
Screenshot from 2020-11-18 12-59-02
Screenshot from 2020-11-18 12-58-50

### Preview Earlier
Screenshot from 2020-11-18 13-00-15

### CODE REVIEW

**Comment by brtwrst** [comment]
Big Issues to start:
* For me this is in no way more readable or better than just linking to the stackoverflow search page itself. The Pagination feels a bit clunky here and my eyes were often drawn to the blue links instead of the actual title of the search result. 
* When testing this it was very hard to discern what lies behind each search result and this means i have to click on many links to find what i need (this is a common problem of stackoverflow in general not related to the command here). 
* This leads to some bad UX when using the Discord Desktop app because each click will pop up a message and ultimately your browser. Then to go back you have to close/minimize the browser to try the next link. (Don't even try this on mobile - constant app switching sucks) 
* The current stackoverflow command which just opens your browser once and you have the search results right there is much nicer in my mind even if it doesn't have a flashy embed with reactions. 
* You have some API key hard coded in the URL - not sure what that is about. As far as i know the stackoverflow API uses an oauth2 flow to authenticate applications. I'm not up to date on the restrictions of the Stackoverflow API and if you have to set up your own account and authenticate through that. But hard coding your own api key when you submit to a repo is most certainly not what you want to do.

That said i do like the idea of the pagination and i'm sure it can be used for something at some point. But this just isn't it.

Here are some other (meta) remarks about the PR that might be helpful to you in the future:
* Fix conflicts before submitting.
* There is no reason to do this stuff in 10 commits especially if 5 of them don't do anything. Clean it up (remove unused imports, remove unneeded comments ...) and squash it down to 1 commit.
* Get to know the codebase a little before submitting something.
  - You are using `logging` and are logging stuff a bunch of times throughout your code. There is no logging in the existing code. (In fact when i tested it, one logging command was causing an Exception and i had to remove all logging code before it worked)
  - You are using `bot` instead of `client` like all the other cogs do
  - You are not providing docstrings for you commands this means there will be no description when people call `felix help` on your command
  - There are a few instances where your code goes against the code styling guideleines https://github.com/engineer-man/felix#code-styling--ide-settings

**Comment by Shivansh-007** [comment]
Sure! I will fix those meta remarks, and see if i can find any way to get a bit description about the question too :D !

**Comment by Shivansh-007** [comment]
Closing this for now !

**Comment by brtwrst** [comment]
I think that, even with a small descriprion, it won't be an improvement over the stackoverflow search page itself because of the other issues i mentioned.

**Pull request closed without merging**
